#!/usr/bin/env bash
export TERM=screen-256color
tmux new-session -s cult -d -n 'Cult' 'tree; ./skel/roles/all/files/cult-motd; bash'

# We do the ctrl-c thing ourself, so it acts like one unit.
tmux set remain-on-exit on
tmux bind -n C-c kill-session

# Tab beteen panes
tmux bind -n Tab select-pane -t ':.+'

tmux split-window -h -b -l 25 -t cult "cat /etc/passwd | grep -v '^#' | cut -d: -f1 | ../../listpager/listpager | nc localhost 4500"
tmux attach -t cult
