#!/usr/bin/env bash

_cult() {
  COMPREPLY=( $(${COMP_WORDS[0]} '--*-completion-bash' \
                ${COMP_CWORD} ${COMP_LINE}) )
  return 0
}

complete -F _cult cult

# A little help for local dev
complete -F _cult ./cult
