#!/usr/bin/env bash
set -e

# This will be the first (normal) Task to be run on your new server.  Rename
# it, and make it do something useful.

# This file will be processed by ERB right before it's shipped to a Node, so
# you can customize it based on the node, roles, project, etc.

# The ERB helper has quite a few methods for shell-escaping, for example:

# "e" does shell slash-escaping, e.g., I\'m\ Awesome.  Importantly, it will
# also escape $ with \$.  It is the most general-purpose for shell scripts,
# and should be your go-to, even though its results are uglier.
# AKA: slash
echo <%= node.name.e %>

# The "q" method quotes a string with double-quotes.  AKA "dq" and "dquote".
# Quote characters are escaped with a slash, e.g., \"
# AKA: dq, dquote
echo <%= node.name.q %>

# The "sq" method single-quotes the string.  This usually never what you want
# in shell-script context, but comes in handy with config files.  We just
# happen to know it'll work here.  Single-quotes are escaped with a slash,
# which shells don't like.
# AKA: squote
echo <%= node.name.sq %>


# The same methods work on Array (over each item), and have an optional
# separator argument, which defaults to ' '
echo <%= node.roles.sq %>

# This script executes in the task directory, so files are accessible as
# "files/something".  Text files in files/ are also pre-processed through IRB,
# with the same context.
