#!/usr/bin/env bash
set -e
LEADER_FILE=~cult/cult/leader-of

<% leader_of = roles.select {|r| node.zone_leader?(r) }.map(&:name) %>

<% if leader_of.empty? %>
  rm -f "$LEADER_FILE"
<% else %>
  echo <%= leader_of.join(" ").sq %> | tee "$LEADER_FILE"
<% end %>
