#!/bin/sh
set -e

# Create the new account Cult will use for normal tasks
adduser --disabled-password --gecos 'Cult Deployment Account' cult

# Copy root's authorized_keys from the provision process to cult
mkdir -p /home/cult/.ssh
mv "$HOME/.ssh/authorized_keys" /home/cult/.ssh
chown -R cult:cult /home/cult/.ssh
chmod -R 0700 /home/cult/.ssh
chmod -R 0600 /home/cult/.ssh/*

# cult needs super-user powers
echo 'cult ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/cult-nopasswd

# Disable root account
passwd -l root

# That dude can't login anymore via SSH, either.
sed -i.bak -e 's/^PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config

systemctl reload sshd.service
