#!/usr/bin/env bash
set -e

# Here's an example that sets the node's hostname.  Notice that this file is
# pre-processed by ERB on a per-node basis before it's shipped to the node.

sudo hostname <%= esc(node.name) %>

# Now we make it stick
hostname | sudo tee /etc/hostname
